version: "3"
services:
  app:
    image: node:14
    volumes:
      - .:/workspace:delegated
      - node_modules:/workspace/node_modules
    command: tail -f /dev/null
    working_dir: /workspace
    environment:
          - CHOKIDAR_USEPOLLING=true
volumes: 
  node_modules:
