version: "3"
services:
  app:
    image: node:16
    volumes:
      - .:/workspace:delegated
    command: tail -f /dev/null
    working_dir: /workspace
    environment:
      - CHOKIDAR_USEPOLLING=true
